server:
  port: 8000
spring:
  profiles:
    active: dev
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active:dev}
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:service-order.properties?group=order

logging:
  level:
    xyz.ljosh.order.feign: debug
